language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  #- "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
notifications:
  email: false
  
# command to install dependencies
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
install:
  #$TRAVIS_PYTHON_VERSION
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib pandas statsmodels nose
  # Coverage packages are on my binstar channel
  # - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - conda install --yes pep8 python-coveralls
  - python setup.py install
# command to run tests
script: #nosetests
  #- nosetests
  - THEANO_FLAGS=floatX=float32 nosetests --with-coverage --cover-package=theanets --logging-level=INFO
